version: "3.8"

services:
  node-app:
    container_name: express-node-app-container
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./.env  # Ensure this file exists and contains required environment variables
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db  # Persist MongoDB data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false  # Disable basic authentication
    depends_on:
      - mongo

  redis:
    image: redis
    restart: always
    volumes:
      - redis-data:/data  # Persist Redis data

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Ensure this file exists
    ports:
      - "8080:80"
    depends_on:
      - node-app

volumes:
  mongo-db:  # Volume for MongoDB data
  redis-data:  # Volume for Redis data